v2212_task:
  container:
    image: gcc
  test_script: 
    - wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | bash
    - apt-get install -qq openfoam${OF_VERS}-default
    - /usr/bin/openfoam2112 wmake
v2112_task:
  container:
    image: opencfd/openfoam2112-dev
  test_script: 
    - /usr/bin/openfoam2112 wmake
