latest_task:
  container:
    image: opencfd/openfoam-dev:latest
  test_script:
    - /usr/bin/openfoam2212 wmake
v2212_task:
  container:
    image: ubuntu:jammy
  test_script:
    - apt-get update
    - apt-get install -y wget 
    - wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | bash
    - apt-get install -qq openfoam2212-dev
    - /usr/bin/openfoam2212 wmake
v2112_task:
  container:
    image: opencfd/openfoam2112-dev
  test_script: 
    - /usr/bin/openfoam2112 wmake
