name: Compile

# Controls when the action will run. 
on:
  push:
     branches: [master]
  
jobs:
  v2212:
      name: "v2212"
      runs-on: ubuntu-20.04
      steps:
        - name: Setup env.
          uses: wei/wget@v1
          with:
             args: https://develop.openfoam.com/packaging/containers/-/raw/main/openfoam-docker ${{ github.workspace }}
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
        - name: Compile
          run: |
            ${{ github.workspace }}/openfoam-docker / wmake

