name: Compile

# Controls when the action will run. 
on:
  push:
     branches: [master]
  
jobs:
  v2212:
      name: "v2212"
      runs-on: ubuntu-20.04
      steps:
        - name: Setup env.
          run: |
            curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
            sudo apt-get install openfoam2212-dev
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 1
        - name : ls
          run: |
            ls /usr/lib/openfoam/openfoam2212/etc/
        - name: Compile
          run: |
            . /usr/lib/openfoam/openfoam2212/etc/bashrc
            wmake
